identidock:
  build: .
  ports:
    - "5000:5000"
  environment:
    ENV: DEV
  volumes:
    - ./app:/app
  links:
    - dnmonster
    - redis
  container_name: "identidock"

dnmonster:
  image: amouat/dnmonster:1.0
  container_name: "dnmonster"

redis:
  image: redis:3.0
